CREATE TABLE tb_cliente ( id_cliente NUMBER PRIMARY KEY, 
                          nome VARCHAR2(100) NOT NULL, 
                          email VARCHAR2(100) UNIQUE, 
                          cep VARCHAR2(8), 
                          logradouro VARCHAR2(150), 
                          bairro VARCHAR2(100), 
                          cidade VARCHAR2(100), 
                          uf VARCHAR2(2), 
                          ativo VARCHAR2(1) DEFAULT '1', 
                          dt_criacao DATE NOT NULL, 
                          login_criacao VARCHAR2(30) NOT NULL,
                          dt_atualizacao DATE,
                          login_atualizacao VARCHAR2(30) );

COMMENT ON COLUMN TB_CLIENTE.ID_CLIENTE IS 'Identificador do Cliente';
COMMENT ON COLUMN TB_CLIENTE.NOME IS 'Nome do Cliente';
COMMENT ON COLUMN TB_CLIENTE.EMAIL IS 'Email do Cliente';
COMMENT ON COLUMN TB_CLIENTE.CEP IS 'CEP';
COMMENT ON COLUMN TB_CLIENTE.LOGRADOURO IS 'Logradouro';
COMMENT ON COLUMN TB_CLIENTE.BAIRRO IS 'Bairro';
COMMENT ON COLUMN TB_CLIENTE.CIDADE IS 'Cidade';
COMMENT ON COLUMN TB_CLIENTE.UF IS 'Estado da Federacao';
COMMENT ON COLUMN TB_CLIENTE.ATIVO IS 'Status do Registro';
COMMENT ON COLUMN TB_CLIENTE.DT_CRIACAO IS 'Data da Criacao';
COMMENT ON COLUMN TB_CLIENTE.LOGIN_CRIACAO IS 'Usuario da Criacao';
COMMENT ON COLUMN TB_CLIENTE.DT_ATUALIZACAO IS 'Data da Atualizacao';
COMMENT ON COLUMN TB_CLIENTE.LOGIN_ATUALIZACAO IS 'Usuario da Atualizacao';

CREATE INDEX IDX_CLIENTE_NOME on TB_CLIENTE (NOME);

ALTER TABLE TB_CLIENTE ADD CONSTRAINT CLIENTE_PK PRIMARY KEY (ID_CLIENTE) USING INDEX;

ALTER TABLE TB_CLIENTE ADD CONSTRAINT CLIENTE_EMAIL_UK UNIQUE (EMAIL) USING INDEX;

ALTER TABLE TB_CLIENTE 
ADD CONSTRAINT CLIENTE_UF_000
CHECK (UF IN ('AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'));

ALTER TABLE TB_CLIENTE
ADD CONSTRAINT CLIENTE_ATIVO_001
CHECK (ATIVO IN ('0','1'));

ALTER TABLE TB_CLIENTE ADD CONSTRAINT fk_cliente_uf FOREIGN KEY (UF) REFERENCES TB_UF(SG_UF);

CREATE INDEX IDX_CLIENTE_UF ON TB_CLIENTE (UF);

-- Criar a sequence 
CREATE SEQUENCE seq_cliente 
START WITH 1 
MAXVALUE 99999999999999999999999999999999999999
INCREMENT BY 1 
NOCACHE 
NOCYCLE; 
/


